"""add_phone_index_and_registration_status

Revision ID: f22cd504402e
Revises: 8f65545faac5
Create Date: 2025-08-07 17:34:59.822295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22cd504402e'
down_revision: Union[str, None] = '8f65545faac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('registration_status', sa.String(length=20), nullable=False, server_default='new'))
    op.create_index('idx_client_phone_active', 'clients', ['phone', 'is_active'], unique=False)
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_index('idx_client_phone_active', table_name='clients')
    op.drop_column('clients', 'registration_status')
    # ### end Alembic commands ###
